# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StaticAnalysis = channel.unary_unary(
                '/ai_service.AiService/StaticAnalysis',
                request_serializer=ai__service__pb2.StaticAnalysisRequest.SerializeToString,
                response_deserializer=ai__service__pb2.StaticAnalysisResponse.FromString,
                _registered_method=True)
        self.ExtractAst = channel.unary_unary(
                '/ai_service.AiService/ExtractAst',
                request_serializer=ai__service__pb2.AstExtractionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.AstExtractionResponse.FromString,
                _registered_method=True)
        self.Reason = channel.unary_unary(
                '/ai_service.AiService/Reason',
                request_serializer=ai__service__pb2.ReasoningRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ReasoningResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/ai_service.AiService/GenerateReport',
                request_serializer=ai__service__pb2.ReportRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.AnalyzeCode = channel.unary_unary(
                '/ai_service.AiService/AnalyzeCode',
                request_serializer=ai__service__pb2.CodeAnalysisRequest.SerializeToString,
                response_deserializer=ai__service__pb2.CodeAnalysisResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ai_service.AiService/Health',
                request_serializer=ai__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class AiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StaticAnalysis(self, request, context):
        """Phase 1 Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractAst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reason(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeCode(self, request, context):
        """Legacy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StaticAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticAnalysis,
                    request_deserializer=ai__service__pb2.StaticAnalysisRequest.FromString,
                    response_serializer=ai__service__pb2.StaticAnalysisResponse.SerializeToString,
            ),
            'ExtractAst': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractAst,
                    request_deserializer=ai__service__pb2.AstExtractionRequest.FromString,
                    response_serializer=ai__service__pb2.AstExtractionResponse.SerializeToString,
            ),
            'Reason': grpc.unary_unary_rpc_method_handler(
                    servicer.Reason,
                    request_deserializer=ai__service__pb2.ReasoningRequest.FromString,
                    response_serializer=ai__service__pb2.ReasoningResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=ai__service__pb2.ReportRequest.FromString,
                    response_serializer=ai__service__pb2.ReportResponse.SerializeToString,
            ),
            'AnalyzeCode': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCode,
                    request_deserializer=ai__service__pb2.CodeAnalysisRequest.FromString,
                    response_serializer=ai__service__pb2.CodeAnalysisResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ai__service__pb2.HealthRequest.FromString,
                    response_serializer=ai__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_service.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StaticAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/StaticAnalysis',
            ai__service__pb2.StaticAnalysisRequest.SerializeToString,
            ai__service__pb2.StaticAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractAst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/ExtractAst',
            ai__service__pb2.AstExtractionRequest.SerializeToString,
            ai__service__pb2.AstExtractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reason(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/Reason',
            ai__service__pb2.ReasoningRequest.SerializeToString,
            ai__service__pb2.ReasoningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/GenerateReport',
            ai__service__pb2.ReportRequest.SerializeToString,
            ai__service__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/AnalyzeCode',
            ai__service__pb2.CodeAnalysisRequest.SerializeToString,
            ai__service__pb2.CodeAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/Health',
            ai__service__pb2.HealthRequest.SerializeToString,
            ai__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
